package com.nstudio.kanjipractice;

import java.util.ArrayList;
import java.util.Arrays;

public class CtrlKanji {
    // N5 kanjis declaration

    private ArrayList<Kanji> kanjis_N5 = new ArrayList<Kanji>(Arrays.asList(
            new Kanji(1 ,"日","nichi, jitsu","ニチ, ジツ","hi, -bi, -ka","ひ, -び, -か","day, sun, Japan, counter for days", false),
            new Kanji(2 ,"一","ichi","イチ","hito(tsu)","ひと(つ)","one", false),
            new Kanji(3 ,"国","koku","コク","kuni","くに","country", false),
            new Kanji(4 ,"人","jin, nin","ジン、 ニン","hito","ひと","person", false),
            new Kanji(5 ,"年","nen","ネン","toshi","とし","year, counter for years", false),
            new Kanji(6 ,"大","dai, tai","ダイ、 タイ","oo(kii)","おお(きい)","large, big", false),
            new Kanji(7 ,"十","juu","ジュウ","tou, to","とお、 と","ten, 10", false),
            new Kanji(8 ,"二","ni, ji","ニ、 ジ","futa(tsu)","ふた(つ)","two, 2", false),
            new Kanji(9 ,"本","hon","ホン","moto","もと","book, present, true, counter for long cylindrical things", false),
            new Kanji(10 ,"中","chuu","チュウ","naka, uchi, ata(ru)","なか、 うち、 あた(る)","in, inside, middle, mean, center", false),
            new Kanji(11 ,"長","chou","チョウ","naga(i), osa","なが(い)、 おさ","long, leader, superior, senior", false),
            new Kanji(12 ,"出","shutsu, sui","シュツ、 スイ","de(ru), da(su), i(deru)","で(る)、 だ(す)、 い(でる)","exit, leave, go out", false),
            new Kanji(13 ,"三","san","サン","mi(tsu)","み(つ)","three, 3", false),
            new Kanji(14 ,"時","ji","ジ","toki, doki","とき、 -どき","time, hour", false),
            new Kanji(15 ,"行","kou, gyou, an","コウ、 ギョウ、 アン","i(ku), yu(ku), okona(u)","い(く)、 ゆ(く)、 おこな(う)","going, journey, carry out, line, row", false),
            new Kanji(16 ,"見","ken","ケン","mi(ru), mi(seru)","み(る)、 み(せる)","see, hopes, chances, idea, opinion, look at, visible", false),
            new Kanji(17 ,"月","getsu, gatsu","ゲツ、 ガツ","tsuki","つき","month, moon", false),
            new Kanji(18 ,"分","bun, fun, bu","ブン、 フン、 ブ","wa(keru)","わ(ける)","part, minute of time, understand", false),
            new Kanji(19 ,"後","go, kou","ゴ、 コウ","nochi, ushi(ro), ato","のち、 うし(ろ)、 あと","behind, back, later", false),
            new Kanji(20 ,"前","zen","ゼン","mae","まえ","in front, before", false),
            new Kanji(21 ,"生","sei, shou","セイ、 ショウ","i(kiru), u(mu), o(u), ha(eru), nama","い(きる)、 う(む)、 お(う)、 は(える)、 なま","life, genuine, birth", false),
            new Kanji(22 ,"五","go","ゴ","itsu(tsu)","いつ(つ)","five, 5", false),
            new Kanji(23 ,"間","kan, ken","カン、 ケン","aida, ma, ai","あいだ、 ま、 あい","interval, space", false),
            new Kanji(24 ,"上","jou, shou, shan","ジョウ、 ショウ、 シャン","ue, uwa, kami, a(geru), nobo(ru), tatematsu(ru)","うえ、 うわ-、 かみ、 あ(げる)、 のぼ(る)、 たてまつ(る)","above, up", false),
            new Kanji(25 ,"東","tou","トウ","higashi","ひがし","east", false),
            new Kanji(26 ,"四","shi","シ","yo(tsu), yon","よ(つ)、 よん","four, 4", false),
            new Kanji(27 ,"今","kon, kin","コン、 キン","ima","いま","now; the present", false),
            new Kanji(28 ,"金","kin, kon, gon","キン、 コン、 ゴン","kane, kana, gane","かね、 かな-、 -がね","gold", false),
            new Kanji(29 ,"九","kyuu, ku","キュウ、 ク","kokono(tsu)","ここの(つ)","nine, 9", false),
            new Kanji(30 ,"入","nyuu","ニュウ","i(ru), hai(ru)","い(る)、はい(る)","enter, insert", false),
            new Kanji(31 ,"学","gaku","ガク","mana(bu)","まな(ぶ)","study, learning, science", false),
            new Kanji(32 ,"高","kou","コウ","taka(i)","たか(い)","tall, high, expensive", false),
            new Kanji(33 ,"円","en","エン","maru(i)","まる(い)","circle, yen, round", false),
            new Kanji(34 ,"子","shi, su, tsu","シ、 ス、 ツ","ko, ne","こ、 ね","child", false),
            new Kanji(35 ,"外","gai, ge","ガイ、 ゲ","soto, hoka, hazu-, to-","そと、 ほか、 はず(す)、 と-","outside", false),
            new Kanji(36 ,"八","hachi","ハチ","ya(tsu), you","や(つ)、 よう","eight, 8", false),
            new Kanji(37 ,"六","roku","ロク","mu(tsu), mui","む(つ)、 むい","six, 6", false),
            new Kanji(38 ,"下","ka, ge","カ、 ゲ","shita, shimo, moto, sa(geru), kuda(ru), o(rosu)","した、 しも、 もと、 さ(げる)、 くだ(る)、 お(ろす)","below, down, descend, give, low, inferior", false),
            new Kanji(39 ,"来","rai, tai","ライ、 タイ","kuru, kitaru, ki, ko","く(る)、 きた(る)、 き、 こ","come, due, next, cause, become", false),
            new Kanji(40 ,"気","ki, ke","キ、 ケ","iki","いき","spirit, mind, air, atmosphere, mood", false),
            new Kanji(41 ,"小","shou","ショウ","chii(sai), ko-, o-, sa-","ちい(さい)、 こ-、 お-、 さ-","little, small", false),
            new Kanji(42 ,"七","shichi","シチ","nana(tsu), nano","なな(つ)、 なの","seven, 7", false),
            new Kanji(43 ,"山","san, sen","サン、 セン","yama","やま","mountain", false),
            new Kanji(44 ,"話","wa","ワ","hana(su), hanashi","はな(す)、 はなし","tale, talk", false),
            new Kanji(45 ,"女","jo","ジョ","onnna, me","おんな、 め","woman, female", false),
            new Kanji(46 ,"北","hoku","ホク","kita","きた","north", false),
            new Kanji(47 ,"午","go","ゴ","uma","うま","noon, sign of the horse", false),
            new Kanji(48 ,"百","hyaku, byaku","ヒャク、 ビャク","momo","もも","hundred", false),
            new Kanji(49 ,"書","sho","ショ","kaku","か(く)","write", false),
            new Kanji(50 ,"先","sen","セン","saki, ma(zu)","さき、 ま(ず)","before, ahead, previous, future, precedence", false),
            new Kanji(51 ,"名","mei, myou","メイ、 ミョウ","na","な","name, noted, distinguished, reputation", false),
            new Kanji(52 ,"川","sen","セン","kawa","かわ","river, stream", false),
            new Kanji(53 ,"千","sen","セン","chi","ち","thousand", false),
            new Kanji(54 ,"水","sui","スイ","mizu","みず","water", false),
            new Kanji(55 ,"半","han","ハン","naka(ba)","なか(ば)","half, middle, odd number, semi-", false),
            new Kanji(56 ,"男","dan, nan","ダン、 ナン","otoko, o","おとこ、 お","male, man", false),
            new Kanji(57 ,"西","sei, sai","セイ、 サイ","nishi","にし","west", false),
            new Kanji(58 ,"電","den","デン","","","electricity, electric powered", false),
            new Kanji(59 ,"校","kou","コウ","","","school, exam", false),
            new Kanji(60 ,"語","go","ゴ","kata(ru)","かた(る)","word, speech, language", false),
            new Kanji(61 ,"土","do, to","ド、 ト","tsuchi","つち","soil, earth, ground", false),
            new Kanji(62 ,"木","boku, moku","ボク、 モク","ki, ko","き、 こ-","tree, wood", false),
            new Kanji(63 ,"聞","bun, mon","ブン、 モン","ki(ku)","き(く)","to hear; to listen; to ask", false),
            new Kanji(64 ,"食","shoku, jiki","ショク、 ジキ","k(u), ta(beru), ha(mu)","く(う)、 た(べる)、 は(む)","eat, food", false),
            new Kanji(65 ,"車","sha","シャ","kuruma","くるま","car, wheel", false),
            new Kanji(66 ,"何","ka","カ","nani, nan","なに、 なん","what", false),
            new Kanji(67 ,"南","nan, na","ナン、 ナ","minami","みなみ","south", false),
            new Kanji(68 ,"万","man, ban","マン、 バン","","","ten thousand, 10,000", false),
            new Kanji(69 ,"毎","mai","マイ","goto(ni)","ごと(に)","every", false),
            new Kanji(70 ,"白","haku, byaku","ハク、 ビャク","shiro(i)","しろ(い)","white", false),
            new Kanji(71 ,"天","ten","テン","amatsu","あまつ","heavens, sky, imperial", false),
            new Kanji(72 ,"母","bo","ボ","haha, kaa","はは、 かあ","mother", false),
            new Kanji(73 ,"火","ka","カ","hi, bi, ho","ひ、 -び、 ほ-","fire", false),
            new Kanji(74 ,"右","u, yuu","ウ、 ユウ","migi","みぎ","right", false),
            new Kanji(75 ,"読","doku, toku, tou","ドク、 トク、 トウ","yo(mu)","よ(む)","to read", false),
            new Kanji(76 ,"友","yuu","ユウ","tomo","とも","friend", false),
            new Kanji(77 ,"左","sa, sha","サ、 シャ","hidari","ひだり","left", false),
            new Kanji(78 ,"休","kyuu","キュウ","yasu(mu)","やす(む)","rest, day off, retire, sleep", false),
            new Kanji(79 ,"父","fu","フ","chichi, tou","ちち、 とう","father", false),
            new Kanji(80 ,"雨","u","ウ","ame, ama","あめ、 あま","rain", false)
    ));

    // N4 Kanji declaration
    private ArrayList<Kanji> kanjis_N4 = new ArrayList<Kanji>(Arrays.asList(
            new Kanji(1 ,"会","kai","カイ","a(u)","あ(う)","meeting; meet", false),
            new Kanji(2 ,"同","dou","ドウ","onaji","おな(じ)","same, agree, equal", false),
            new Kanji(3 ,"事","ji","ジ","koto","こと","matter, thing, fact, business, reason, possibly", false),
            new Kanji(4 ,"自","ji, shi","ジ、 シ","mizuka(ra)","みずか(ら)","oneself", false),
            new Kanji(5 ,"社","sha","シャ","yashiro","やしろ","company, firm, office, association, shrine", false),
            new Kanji(6 ,"発","hatsu, hotsu","ハツ、 ホツ","","","departure, discharge, emit, start from", false),
            new Kanji(7 ,"者","sha","シャ","mono","もの","someone, person", false),
            new Kanji(8 ,"地","chi, ji","チ、 ジ","","","ground, earth", false),
            new Kanji(9 ,"業","gyou","ギョウ","waza","わざ","business, vocation, arts, performance", false),
            new Kanji(10 ,"方","hou","ホウ","kata","かた","direction, person, alternative", false),
            new Kanji(11 ,"新","shin","シン","atara(shii), ara(ta)","あたら(しい)、 あら(た)","new", false),
            new Kanji(12 ,"場","jou","ジョウ","ba","ば","location, place", false),
            new Kanji(13 ,"員","in","イン","","","employee, member, number, the one in charge", false),
            new Kanji(14 ,"立","ritsu","リツ","ta(tsu)","た(つ)","stand up, rise", false),
            new Kanji(15 ,"開","kai","カイ","hira(ku), a(keru)","ひら(く)、 あ(ける)","open, unfold, unseal", false),
            new Kanji(16 ,"手","shu","シュ","te","て","hand", false),
            new Kanji(17 ,"力","ryoku, riki","リョク、 リキ","chikara","ちから","power, strength, strong, strain, bear up, exert", false),
            new Kanji(18 ,"問","mon","モン","to(u)","と(う)","question, ask, problem", false),
            new Kanji(19 ,"代","dai","ダイ","ka(wari)","か(わり)","substitute, change, convert, replace, period", false),
            new Kanji(20 ,"明","mei, myou","メイ、 ミョウ","aka(rui)","あか(るい)","bright, light", false),
            new Kanji(21 ,"動","dou","ドウ","ugo(ku)","うご(く)","move, motion, change", false),
            new Kanji(22 ,"京","kyou, kei, kin","キョウ、 ケイ、 キン","miyako","みやこ","capital", false),
            new Kanji(23 ,"目","moku, boku","モク、 ボク","me","め","eye, class, look, insight, experience", false),
            new Kanji(24 ,"通","tsuu","ツウ","too(ru), kayo(u)","とお(る)、かよ(う)","traffic, pass through, avenue, commute", false),
            new Kanji(25 ,"言","gen, gon","ゲン、 ゴン","i(u), koto","い（う）、 こと","say, word", false),
            new Kanji(26 ,"理","ri","リ","","","logic, arrangement, reason, justice, truth", false),
            new Kanji(27 ,"体","tai","タイ","karada","からだ","body, substance, object, reality", false),
            new Kanji(28 ,"田","den","デン","ta","た","rice field, rice paddy", false),
            new Kanji(29 ,"主","shu","シュ","nushi, omo","ぬし、 おも","lord, chief, master, main thing, principal", false),
            new Kanji(30 ,"題","dai","ダイ","","","topic, subject", false),
            new Kanji(31 ,"意","i","イ","","","idea, mind, heart, taste, thought", false),
            new Kanji(32 ,"不","fu, bu","フ、 ブ","","","negative, non-, bad", false),
            new Kanji(33 ,"作","saku, sa","サク、 サ","tsuku(ru)","つく(る)","make, production, prepare, build", false),
            new Kanji(34 ,"用","you","ヨウ","mochi(iru)","もち(いる)","utilize, business, service, use, employ", false),
            new Kanji(35 ,"度","do, taku","ド、 タク","tabi, ta(i)","たび、 た(い)","degrees, occurrence, time, counter for occurrences", false),
            new Kanji(36 ,"強","kyou, gou","キョウ、 ゴウ","tsuyo(i)","つよ(い)","strong", false),
            new Kanji(37 ,"公","kou","コウ","","","public, prince, official, governmental", false),
            new Kanji(38 ,"持","ji","ジ","mo(tsu)","も(つ)","hold, have", false),
            new Kanji(39 ,"野","ya","ヤ","no","の","plains, field, rustic, civilian life", false),
            new Kanji(40 ,"以","i","イ","mo(tte)","もっ(て)","by means of, because, in view of, compared with", false),
            new Kanji(41 ,"思","shi","シ","omo(u)","おも(う)","think", false),
            new Kanji(42 ,"家","ka","カ","ie, ya, uchi","いえ、 や、 うち","house, home, family, professional, expert", false),
            new Kanji(43 ,"世","sei, se","セイ、 セ","yo","よ","generation, world, society, public", false),
            new Kanji(44 ,"多","ta","タ","oo(i)","おお(い)","many, frequent, much", false),
            new Kanji(45 ,"正","sei, shou","セイ、 ショウ","tada(shii), masa(ni)","ただ(しい)、 まさ(に)","correct, justice, righteous", false),
            new Kanji(46 ,"安","an","アン","yasu(i)","やす(い)","safe, peaceful, cheap", false),
            new Kanji(47 ,"院","in","イン","","","institution, temple, mansion, school", false),
            new Kanji(48 ,"心","shin","シン","kokoro","こころ","heart, mind, spirit", false),
            new Kanji(49 ,"界","kai","カイ","","","world, boundary", false),
            new Kanji(50 ,"教","kyou","キョウ","oshi(eru), oso(waru)","おし(える)、 おそ(わる)","teach, faith, doctrine", false),
            new Kanji(51 ,"文","bun, mon","ブン、 モン","fumi","ふみ","sentence, literature, style, art", false),
            new Kanji(52 ,"元","gen, gan","ゲン、 ガン","moto","もと","beginning, former time, origin", false),
            new Kanji(53 ,"重","juu, chou","ジュウ、 チョウ","omo(i), kasa(neru)","おも(い)、 かさ(ねる)","heavy, important, esteem, respect", false),
            new Kanji(54 ,"近","kin","キン","chika(i)","ちか(い)","near, early, akin, tantamount", false),
            new Kanji(55 ,"考","kou","コウ","kanga(eru)","かんが(える)","consider, think over", false),
            new Kanji(56 ,"画","ga, kaku","ガ、 カク","kaku(suru)","かく(する)","brush-stroke, picture", false),
            new Kanji(57 ,"海","kai","カイ","umi","うみ","sea, ocean", false),
            new Kanji(58 ,"売","bai","バイ","u(ru)","う(る)","sell", false),
            new Kanji(59 ,"知","chi","チ","shi(ru)","し(る)","know, wisdom", false),
            new Kanji(60 ,"道","dou","ドウ","michi","みち","road-way, street, district, journey, course", false),
            new Kanji(61 ,"集","shuu","シュウ","atsu(meru)","あつ(める)","gather, meet", false),
            new Kanji(62 ,"別","betsu","ベツ","waka(reru), wa(keru)","わか(れる)、 わ(ける)","separate, branch off, diverge", false),
            new Kanji(63 ,"物","butsu, motsu","ブツ、 モツ","mono","もの","thing, object, matter", false),
            new Kanji(64 ,"使","shi","シ","tsuka(u)","つか(う)","use, order, messenger, ambassador", false),
            new Kanji(65 ,"品","hin","ヒン","shina","しな","goods, refinement, dignity, article", false),
            new Kanji(66 ,"計","kei","ケイ","haka(ru)","はか(る)","plot, plan, scheme, measure", false),
            new Kanji(67 ,"死","shi","シ","shi(nu)","し(ぬ)","death, die", false),
            new Kanji(68 ,"特","toku","トク","","","special", false),
            new Kanji(69 ,"私","shi","シ","watakushi, watashi","わたくし、 わたし","private, I, me", false),
            new Kanji(70 ,"始","shi","シ","haji(meru)","はじ(める)","commence, begin", false),
            new Kanji(71 ,"朝","chou","チョウ","asa","あさ","morning", false),
            new Kanji(72 ,"運","un","ウン","hako(bu)","はこ(ぶ)","carry, luck, destiny, fate, transport", false),
            new Kanji(73 ,"終","shuu","シュウ","o(waru)","お(わる)","end, finish", false),
            new Kanji(74 ,"台","dai, tai","ダイ、 タイ","utena","うてな","pedestal, a stand, counter for machines and vehicles", false),
            new Kanji(75 ,"広","kou","コウ","hiro(i)","ひろ(い)","wide, broad, spacious", false),
            new Kanji(76 ,"住","juu, chuu","ジュウ、 チュウ","su(mu)","す(む)","dwell, reside, live, inhabit", false),
            new Kanji(77 ,"無","mu, bu","ム、 ブ","na(i)","な(い)","nothingness, none, ain't, nothing, nil, not", false),
            new Kanji(78 ,"真","shin","シン","ma, makoto","ま、 まこと","true, reality, Buddhist sect", false),
            new Kanji(79 ,"有","yuu, u","ユウ、 ウ","a(ru)","あ(る)","possess, have, exist, happen", false),
            new Kanji(80 ,"口","kou","コウ","kuchi","くち","mouth", false),
            new Kanji(81 ,"少","shou","ショウ","suku(nai), suko(shi)","すく(ない)、 すこ(し)","few, little", false),
            new Kanji(82 ,"町","chou","チョウ","machi","まち","town, village, block, street", false),
            new Kanji(83 ,"料","ryou","リョウ","","","fee, materials", false),
            new Kanji(84 ,"工","kou, ku, gu","コウ、 ク、 グ","","","craft, construction", false),
            new Kanji(85 ,"建","ken, kon","ケン、 コン","ta(teru)","た(てる)","build", false),
            new Kanji(86 ,"空","kuu","クウ","sora, kara, a(ku), su(ku), muna(shii)","そら、 から、 あ(く)、 す(く)、 むな(しい)","empty, sky, void, vacant, vacuum", false),
            new Kanji(87 ,"急","kyuu","キュウ","iso(gu)","いそ(ぐ)","hurry, emergency, sudden, steep", false),
            new Kanji(88 ,"止","shi","シ","to(maru), todo(maru), ya(meru), yo(su)","と(まる)、 とど(まる)、 や(める)、 よ(す)","stop, halt", false),
            new Kanji(89 ,"送","sou","ソウ","oku(ru)","おく(る)","escort, send", false),
            new Kanji(90 ,"切","setsu, sai","セツ、 サイ","ki(ru)","き(る)","cut, cutoff, be sharp", false),
            new Kanji(91 ,"転","ten","テン","koro(garu)","ころ(がる)","revolve, turn around, change", false),
            new Kanji(92 ,"研","ken","ケン","to(gu)","と(ぐ)","polish, study of, sharpen", false),
            new Kanji(93 ,"足","soku","ソク","ashi, ta(riru)","あし、 た(りる)","leg, foot, be sufficient", false),
            new Kanji(94 ,"究","kyuu","キュウ","","","research, study", false),
            new Kanji(95 ,"楽","gaku, raku","ガク、 ラク","tano(shii)","たの(しい)","music, comfort, ease", false),
            new Kanji(96 ,"起","ki","キ","o(kiru), oko(su)","お(きる)、 おこ(す)","wake up, get up; rouse", false),
            new Kanji(97 ,"着","chaku","チャク","ki(ru), tsu(ku)","き(る)、つ(く)","arrive, wear, counter for suits of clothing", false),
            new Kanji(98 ,"店","ten","テン","mise","みせ","store, shop", false),
            new Kanji(99 ,"病","byou","ビョウ","ya(mu)","や(む)","ill, sick", false),
            new Kanji(100 ,"質","shitsu, shichi","シツ、 シチ","tachi, tada(su)","たち、 ただ(す)","substance, quality, matter, temperament", false),
            new Kanji(101 ,"待","tai","タイ","ma(tsu)","ま(つ)","wait, depend on", false),
            new Kanji(102 ,"試","shi","シ","kokoro(miru), tame(su)","こころ(みる)、 ため(す)","test, try, attempt, experiment", false),
            new Kanji(103 ,"族","zoku","ゾク","","","tribe, family", false),
            new Kanji(104 ,"銀","gin","ギン","","","silver", false),
            new Kanji(105 ,"早","sou, sa","ソウ、 サッ","haya(i)","はや(い)","early, fast", false),
            new Kanji(106 ,"映","ei","エイ","utsu(ru), ha(eru)","うつ(る)、 は(える)","reflect, reflection, projection", false),
            new Kanji(107 ,"親","shin","シン","oya, shita(shii)","おや、 した(しい)","parent, intimacy, relative, familiarity", false),
            new Kanji(108 ,"験","ken","ケン","","","verification, effect, testing", false),
            new Kanji(109 ,"英","ei","エイ","","","England, English, hero, outstanding", false),
            new Kanji(110 ,"医","i","イ","","","doctor, medicine", false),
            new Kanji(111 ,"仕","shi","シ","","","attend, doing, official, serve", false),
            new Kanji(112 ,"去","kyo, ko","キョ、 コ","sa(ru)","さ(る)","gone, past, quit, leave, elapse, eliminate", false),
            new Kanji(113 ,"味","mi","ミ","aji","あじ","flavor, taste", false),
            new Kanji(114 ,"写","sha","シャ","utsuru","うつ(る)","copy, be photographed, describe", false),
            new Kanji(115 ,"字","ji","ジ","","","character, letter, word", false),
            new Kanji(116 ,"答","tou","トウ","kota(eru)","こた(える)","solution, answer", false),
            new Kanji(117 ,"夜","ya","ヤ","yo, yoru","よ、 よる","night, evening", false),
            new Kanji(118 ,"音","on","オン","oto, ne","おと、 ね","sound, noise", false),
            new Kanji(119 ,"注","chuu","チュウ","soso(gu), sa(su), tsu(gu)","そそ(ぐ)、 さ(す)、 つ(ぐ)","pour, irrigate, shed (tears), flow into, concentrate on", false),
            new Kanji(120 ,"帰","ki","キ","kae(ru), kae(su)","かえ(る)、 かえ(す)","homecoming, arrive at, lead to, result in", false),
            new Kanji(121 ,"古","ko","コ","furu(i)","ふる(い)","old", false),
            new Kanji(122 ,"歌","ka","カ","uta, uta(u)","うた、 うた(う)","song, sing", false),
            new Kanji(123 ,"買","bai","バイ","ka(u)","か(う)","buy", false),
            new Kanji(124 ,"悪","aku","アク","waru(i)","わる(い)","bad, evil, wrong", false),
            new Kanji(125 ,"図","zu, to","ズ、 ト","haka(ru)","はか(る)","map, drawing, plan, extraordinary", false),
            new Kanji(126 ,"週","shuu","シュウ","","","week", false),
            new Kanji(127 ,"室","shitsu","シツ","muro","むろ","room, apartment, chamber, greenhouse, cellar", false),
            new Kanji(128 ,"歩","ho, bu","ホ、 ブ","aru(ku), ayu(mu)","ある(く)、 あゆ(む)","walk, counter for steps", false),
            new Kanji(129 ,"風","fuu, fu","フウ、 フ","kaze, kaza-","かぜ、 かざ-","wind, air, style, manner", false),
            new Kanji(130 ,"紙","shi","シ","kami","かみ","paper", false),
            new Kanji(131 ,"黒","koku","コク","kuro","くろ","black", false),
            new Kanji(132 ,"花","ka, ke","カ、 ケ","hana","はな","flower", false),
            new Kanji(133 ,"春","shun","シュン","haru","はる","spring", false),
            new Kanji(134 ,"赤","seki, shaku","セキ、 シャク","aka(i)","あか(い)","red", false),
            new Kanji(135 ,"青","sei, shou","セイ、 ショウ","ao(i)","あお(い)","blue", false),
            new Kanji(136 ,"館","kan","カン","yakata","やかた","building, mansion, large building, palace", false),
            new Kanji(137 ,"屋","oku","オク","ya","や","roof, house, shop, dealer, seller", false),
            new Kanji(138 ,"色","shoku, shiki","ショク、 シキ","iro","いろ","color", false),
            new Kanji(139 ,"走","sou","ソウ","hashi(ru)","はし(る)","run", false),
            new Kanji(140 ,"秋","shuu","シュウ","aki","あき","autumn, fall", false),
            new Kanji(141 ,"夏","ka, ge","カ、 ゲ","natsu","なつ","summer", false),
            new Kanji(142 ,"習","shuu","シュウ","nara(u)","なら(う)","learn", false),
            new Kanji(143 ,"駅","eki","エキ","","","station", false),
            new Kanji(144 ,"洋","you","ヨウ","","","ocean, sea, foreign, Western style", false),
            new Kanji(145 ,"旅","ryo","リョ","tabi","たび","trip, travel", false),
            new Kanji(146 ,"服","fuku","フク","","","clothing, admit, obey", false),
            new Kanji(147 ,"夕","","","yuu","ゆう","evening", false),
            new Kanji(148 ,"借","shaku","シャク","ka(riru)","か(りる)","borrow, rent", false),
            new Kanji(149 ,"曜","you","ヨウ","","","weekday", false),
            new Kanji(150 ,"飲","in","イン","no(mu)","の(む)","drink", false),
            new Kanji(151 ,"肉","niku","ニク","","","meat", false),
            new Kanji(152 ,"貸","tai","タイ","ka(su), kashi","か(す)、 かし","lend", false),
            new Kanji(153 ,"堂","dou","ドウ","","","public chamber, hall", false),
            new Kanji(154 ,"鳥","chou","チョウ","tori","とり","bird, chicken", false),
            new Kanji(155 ,"飯","han","ハン","meshi","めし","meal, rice", false),
            new Kanji(156 ,"勉","ben","ベン","tsuto(meru)","つと(める)","exertion, endeavor, effort", false),
            new Kanji(157 ,"冬","tou","トウ","fuyu","ふゆ","winter", false),
            new Kanji(158 ,"昼","chuu","チュウ","hiru","ひる","daytime, noon", false),
            new Kanji(159 ,"茶","cha, sa","チャ、 サ","","","tea", false),
            new Kanji(160 ,"弟","tei, dai, de","テイ、 ダイ、 デ","otouto","おとうと","younger brother", false),
            new Kanji(161 ,"牛","gyuu","ギュウ","ushi","うし","cow", false),
            new Kanji(162 ,"魚","gyo","ギョ","uo, sakana","うお、 さかな","fish", false),
            new Kanji(163 ,"兄","kyou, kei","キョウ、 ケイ","ani","あに","elder brother", false),
            new Kanji(164 ,"犬","ken","ケン","inu","いぬ","dog", false),
            new Kanji(165 ,"妹","mai","マイ","imouto","いもうと","younger sister", false),
            new Kanji(166 ,"姉","shi","シ","ane","あね","elder sister", false),
            new Kanji(167 ,"漢","kan","カン","","","China", false)
    ));

    public CtrlKanji(){}

    ArrayList<Kanji> getN5Kanjis(){
        return this.kanjis_N5;
    }

    ArrayList<Kanji> getSelectedN5Kanjis(boolean[] selected_kanjis){
        ArrayList<Kanji> kanjis = new ArrayList<Kanji>();
        for(int i = 0; i < kanjis_N5.size(); i++){
            if(selected_kanjis[i])
                kanjis.add(kanjis_N5.get(i));
        }
        return kanjis;
    }

    ArrayList<Kanji> getN4Kanjis(){
        return this.kanjis_N4;
    }

    ArrayList<Kanji> getSelectedN4Kanjis(boolean[] selected_kanjis){
        ArrayList<Kanji> kanjis = new ArrayList<Kanji>();
        for(int i = 0; i < kanjis_N4.size(); i++){
            if(selected_kanjis[i])
                kanjis.add(kanjis_N4.get(i));
        }
        return kanjis;
    }

}
